name: rag_env
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10 # Using Python 3.10 for broader package compatibility
  - polars
  - streamlit
  - pip
  - pip:
      - docling
      - langchain>=0.2.0
      - langchain-openai
      - langchain-community
      - langchain-core
      - pinecone # Corrected package name for Pinecone client v7+
      - langchain-pinecone # Explicitly install langchain-pinecone for integration
      - sentence-transformers
      - python-dotenv
      - beautifulsoup4
